// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessagerChange();
void onAllWindowsChange();
void onIsRainingChange();
void onManualLightChange();
void onWSTATEChange();

String messager;
int allWindows;
bool isRaining;
bool manualLight;
bool w_STATE;

void initProperties(){

  ArduinoCloud.addProperty(messager, READWRITE, ON_CHANGE, onMessagerChange);
  ArduinoCloud.addProperty(allWindows, READWRITE, ON_CHANGE, onAllWindowsChange);
  ArduinoCloud.addProperty(isRaining, READWRITE, ON_CHANGE, onIsRainingChange);
  ArduinoCloud.addProperty(manualLight, READWRITE, ON_CHANGE, onManualLightChange);
  ArduinoCloud.addProperty(w_STATE, READWRITE, ON_CHANGE, onWSTATEChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
