// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3590c270-dbef-4424-bc1d-f7190c29bd5f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMessagerChange();
void onAllWindowsChange();
void onLightValueChange();
void onRainValueChange();
void onIsRainingChange();
void onLightStateChange();
void onManualLightChange();
void onWSTATEChange();

String messager;
int allWindows;
int lightValue;
int rainValue;
bool isRaining;
bool lightState;
bool manualLight;
bool w_STATE;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(messager, READWRITE, ON_CHANGE, onMessagerChange);
  ArduinoCloud.addProperty(allWindows, READWRITE, ON_CHANGE, onAllWindowsChange);
  ArduinoCloud.addProperty(lightValue, READWRITE, ON_CHANGE, onLightValueChange);
  ArduinoCloud.addProperty(rainValue, READWRITE, ON_CHANGE, onRainValueChange);
  ArduinoCloud.addProperty(isRaining, READWRITE, ON_CHANGE, onIsRainingChange);
  ArduinoCloud.addProperty(lightState, READWRITE, ON_CHANGE, onLightStateChange);
  ArduinoCloud.addProperty(manualLight, READWRITE, ON_CHANGE, onManualLightChange);
  ArduinoCloud.addProperty(w_STATE, READWRITE, ON_CHANGE, onWSTATEChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
